//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.12 at 09:41:18 PM VLAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.postlife.com/spring/ws/categories", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.geekbrains.march.market.soap.categories;
