server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:market-core;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

integrations:
  auth-service:
    url: http://localhost:8187/market-auth/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  cart-service:
    url: http://localhost:8190/market-cart/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000